services:
  mysql:
    image: mysql:8.4
    container_name: gritlog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
