name: Main - Format & Test

on:
  push:
    branches: [ main ]

jobs:
  format_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 自動コミットに必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: ktlintFormat (auto-fix)
        run: ./gradlew ktlintFormat --no-daemon

      - name: Auto-commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ktlint): auto format on main"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
          skip_fetch: true

      - name: Unit Test
        run: ./gradlew test --no-daemon
